version: '3.1'
services:
  web:
    image: odoo:17.0
    container_name: padron_web
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - LOG_LEVEL=debug
      - LOG_HANDLER=console
  db:
    image: postgres:14
    container_name: padron_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo

